version: '3'
services:
  app:
    container_name: uppercase
    build: .
    ports: 
      - 8081:8081
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    networks:
      - net

volumes:
  api:

# Networks to be created to facilitate communication between containers
networks:
  net:
    driver: bridge